web-rails/startApp_startup/config/routes.rb
Rails.application.routes.draw do
  
  resources :mobile_app_screens
  resources :mobile_apps
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', 
                                    passwords: 'users/passwords',
                                    :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'welcome/index'
  match '/mobile_apps/build/:id', to: 'mobile_apps#build', as: 'build', :via => [:get,:post], :as => :mobile_apps_build
  match '/mobile_apps/:id', to: 'mobile_apps#show', as: 'show', :via => [:get ], :as => :mobile_apps_show
  match '/mobile_apps/pages/:id/:name', to: 'mobile_apps#new_page', as: 'new_tab', :via => [:get,:post], :as => :mobile_apps_new_page
  match '/mobile_apps/pages/:id/:name', to: 'mobile_apps#delete_page', as: 'delete_page', :via => [:delete], :as => :mobile_apps_delete_page
  match '/mobile_apps/content/:id/:name', to: 'mobile_apps#set_content', as: 'set_content', :via => [:get,:post], :as => :mobile_apps_set_content
  match '/mobile_apps/pages/:id/:name/exists', to: 'mobile_apps#page_exists', as: 'page_exists', :via => [:get], :as => :mobile_apps_page_exists
  match '/versions/:id', to: 'versions#update', as: 'version_update', :via => [:post], :as => :versions_update
  match '/versions/restore/:id', to: 'versions#restore', as: 'version_restore', :via => [:post], :as => :versions_restore
  match '/versions/:id', to: 'versions#index', as: 'versions_index', :via => [:get], :as => :versions_index
  match '/versions/new/:id', to: 'versions#new', as: 'versions_new', :via => [:get, :post], :as => :versions_new

  match '/notifications/:id', to: 'notifications#update', as: 'notification_update', :via => [:post], :as => :notifications_update
  match '/notifications/:id', to: 'notifications#index', as: 'notification_index', :via => [:get], :as => :notifications_index
  match '/notifications/new/:id', to: 'notifications#new', as: 'notification_new', :via => [:get, :post], :as => :notifications_new

  
  match '/mobile_apps/menu/:id', to: 'mobile_apps#menu', as: 'menu', :via => [:get,:post], :as => :mobile_apps_menu

  resources :versions
  resources :notifications

  root 'welcome#index'

end

web-rails/startApp_startup/app/models/mobile_app.rb
class MobileApp < ActiveRecord::Base
	belongs_to :user
	has_many :mobile_app_screens, dependent: :destroy
	has_many :versions, dependent: :destroy

	validates :title, presence: { message: "Title is required" }

	validate :user_app_title_used, :on => [ :create, :update ]
	validate :freeze_title, :on => :update
	validate :freeze_apptype, :on => :update


	def user_app_title_used
		@user = User.find(self.user_id)
		@mobile_apps = @user.mobile_apps.select{|a| a.title == self.title && a.id != self.id}
		if (@mobile_apps.any?)
      		errors.add(:title_already_used, "")
    	end
    end

    def freeze_title
    	errors.add(:title, " cannot be changed") if self.title_changed?
  	end

	def freeze_apptype
		errors.add(:apptype, " cannot be changed") if self.apptype_changed?
	end

end

web-rails/startApp_startup/app/helpers/mobile_apps_helper.rb
module MobileAppsHelper

	def self.create_app(name, userPath, appType)
		FileUtils.mkdir_p(userPath) unless File.directory?(userPath)
        appPath = userPath.join(name);
        modelName = get_model_name(appType);
        modelPath = Rails.root.join('modelos').join(modelName);
        FileUtils.cp_r modelPath, appPath
        replace_on_app_creation(appPath, name, modelName);
        system("cd \"#{appPath}\" && ionic login --email fpiechotka@gmail.com --password 123123 && ionic io init");
        replace_app_id(appPath);
	end

	def self.replace_app_id(appPath)
		appId = get_app_id(appPath)
		replace(appPath.join('src').join('app').join('app.module.ts'), '[APPID]') { |match| appId }
		
	end	

	def self.get_app_id(appPath)
		File.open(appPath.join('ionic.config.json')) do |f|
		  f.each_line do |line|
		    if line =~ /\"app_id\"/
		      return line.scan( /: \"([^>]*)\"/).last.first
		    end
		  end
		end
		return "";
	end


	def self.replace_on_app_creation(appPath, appName, modelName)
		replace(appPath.join('package.json'), modelName) { |match| appName }
		replace(appPath.join('ionic.config.json'), modelName) { |match| appName }
		replace(appPath.join('config.xml'), modelName) { |match| appName }
		replace(appPath.join('plugins/android.json'), modelName) { |match| appName }
		replace(appPath.join('platforms/android/AndroidManifest.xml'), modelName) { |match| appName }
		replace(appPath.join('platforms/android/android.json'), modelName) { |match| appName }
		replace(appPath.join('platforms/android/res/values/strings.xml'), modelName) { |match| appName }
		replace(appPath.join('platforms/android/res/xml/config.xml'), modelName) { |match| appName }

		androidDirectory = appPath.join('platforms/android/src/com/ionicframework')
		oldDirectory = Dir.entries(androidDirectory).sort_by {|x| x.length}.last()
		number = /\d+/.match(oldDirectory)[0]
		FileUtils.mv androidDirectory.join(oldDirectory), androidDirectory.join(appName + number)

		replace(androidDirectory.join(appName + number).join('MainActivity.java'), modelName) { |match| appName }
	end

	def self.get_model_name(appType)
		if(appType == 'tabs')
			return 'moldet'
		else
			return 'moldes'
		end
	end

	def self.new_page(mobileApp, appPath, originalName, appType, type, value)
		tabName = transform_name(originalName)
		
		system("cd \"#{appPath}\" && ionic g page \"#{tabName}\"");

		# modelPath = Rails.root.join('modelos').join('page')
		# tabsPath = appPath.join('src').join('pages');
		# tabPath = tabsPath.join(tabName);
		# FileUtils.mkdir_p(tabPath);
		# FileUtils.cp_r modelPath, tabsPath
		# File.rename(tabsPath.join('page'), tabPath)
		# File.rename(tabPath.join('tab.html'), tabPath.join(tabName + ".html"));
		# #File.rename(tabPath.join('tab.scss'), tabPath.join(tabName + ".scss"));
		# File.rename(tabPath.join('tab.ts'), tabPath.join(tabName + ".ts"));
		# replace(tabPath.join(tabName + ".html"), 'tab') { |match| tabName }
		# tabNameForPage = tabName[0].upcase + tabName[1..tabName.length - 1]		
		# replace(tabPath.join(tabName + ".ts"), 'Tab') { |match| tabNameForPage }
		# replace(tabPath.join(tabName + ".ts"), 'tab') { |match| tabName }
		# #replace(tabPath.join(tabName + ".scss"), 'tab') { |match| tabName }


		if (appType == 'Tabs')
			new_tab(appPath, tabName, originalName)
		else
			new_menu_page(appPath, tabName, originalName)
		end

		content = ""
		case type
		when "2"#custom screen
			@mobile_app_screen = mobileApp.mobile_app_screens.select { |s| s.id.to_s == value }
			if(@mobile_app_screen.present? && @mobile_app_screen.size > 0)
				content= @mobile_app_screen.first.raw_html

				if (@mobile_app_screen.first.wsURL.present?)
					puts "present"
					set_ws_tab(appPath, tabName, mobileApp.title, @mobile_app_screen.first.wsURL)
				else
					puts "not present"
				end
			end
		when "3"#facebook feed
			content = get_fb_content(value)
		when "4"#instagram feed
			content = get_ig_content(value)
		when "5"#twitter feed
			content = get_tw_content(value)
		when "6"#youtube channel
			content = get_yt_content(value)
		when "7"#chat
			content = get_chat_content()
			set_chat_tab(appPath, tabName, mobileApp.title)
		when "8"#Google map
			content = get_map_content(value)
		when "9"#html
			content = value
		end
		set_content(appPath, tabName, content)
		before_reload()
	end

	def self.new_menu_page(appPath, tabName, originalName)
		#app.component.ts
		componentTsPath = appPath.join('src').join('app').join('app.component.ts')
		tabNameForPage = tabName[0].upcase + tabName[1..tabName.length - 1]		
		replace(componentTsPath, '@Component({') { |match| "import { " + tabNameForPage +"Page } from '../pages/" + tabName +"/" + tabName + "';" + "\n" + "#{match}" }
		replace(componentTsPath, /\}((?!,)[\S\s])*];/) { |match| "},\n      { title: '" + originalName + "', component: " + tabNameForPage + "Page }" + "\n" + "    ];" }

		#app.module.ts
		moduleTsPath = appPath.join('src').join('app').join('app.module.ts')
		replace(moduleTsPath, '@NgModule({') { |match| "import { " + tabNameForPage +"Page } from '../pages/" + tabName +"/" + tabName + "';" + "\n" + "#{match}" }
		replace(moduleTsPath, 'MyApp,') { |match| "MyApp,\n    " + tabNameForPage + "Page," }

		#page.html 
		pagePath = appPath.join('src').join('pages').join(tabName).join(tabName + '.html')
		replace(pagePath, '<ion-navbar>') { |match| "#{match}" + '<button ion-button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>' }
    	replace(pagePath, '<ion-title>' + tabName + '</ion-title>'){ |match| "<ion-title>" + originalName + "</ion-title>" }

	end

	def self.new_tab(appPath, tabName, originalName)
		#tabs.html
		tabsPath = appPath.join('src').join('pages').join('tabs').join('tabs.html')
		tabLine = '<ion-tab [root]="tab' + tabName + '" tabTitle="' + originalName +'" tabIcon="' + tabName + '"></ion-tab>' + "\n"
		replace(tabsPath, /<\/ion-tabs>/mi) { |match| tabLine + "#{match}"}

		#tabs.ts
		tabsTsPath = appPath.join('src').join('pages').join('tabs').join('tabs.ts') 
		tabNameForPage = tabName[0].upcase + tabName[1..tabName.length - 1]
		replace(tabsTsPath, 'export class TabsPage {') { |match| "#{match}" + "\n  tab" + tabName + ": any = " + tabNameForPage + "Page;"}
		replace(tabsTsPath, '@Component({') { |match| "import { " + tabNameForPage +"Page } from '../" + tabName +"/" + tabName + "';" + "\n" + "#{match}" }

		#page.html
		pagePath = appPath.join('src').join('pages').join(tabName).join(tabName + '.html')
    	replace(pagePath, '<ion-title>' + tabName + '</ion-title>'){ |match| "<ion-title>" + originalName + "</ion-title>" }

		#app.module.ts
		moduleTsPath = appPath.join('src').join('app').join('app.module.ts')
		replace(moduleTsPath, '@NgModule({') { |match| "import { " + tabNameForPage +"Page } from '../pages/" + tabName + "/" + tabName + "';" + "\n" + "#{match}" }
		replace(moduleTsPath, 'MyApp,') { |match| "MyApp,\n    " + tabNameForPage + "Page," }

	end

	def self.replace(filepath, regexp, *args, &block)
		content = File.read(filepath).gsub(regexp, *args, &block)
		File.open(filepath, 'wb') { |file| file.write(content) }
	end

	def self.set_content(appPath, tabName, content)
		tabPath = appPath.join('src').join('pages').join(tabName).join(tabName + '.html')
		replace(tabPath, /<ion-content padding>\n(.*\n)*<\/ion-content>/) { |match| "<ion-content padding>" + "\n" + content + "\n" + "</ion-content>"}
	end


	def self.delete_page(appPath, originalName, appType)
		tabsPath = appPath.join('src').join('pages');
		tabName = transform_name(originalName)
		count = Dir.entries(tabsPath).delete_if {|i| i == "." || i == ".." || i == "tabs"}.count;
		if(count > 1)
			if (appType == 'Tabs')
				delete_tab(appPath, originalName, tabName)
			else
				delete_menu_page(appPath, originalName, appType, tabName)
			end
			FileUtils.rm_rf(tabsPath.join(tabName))			
		end
		before_reload()
	end

	def self.before_reload
		sleep 9
	end

	def self.delete_menu_page(appPath, originalName, appType, tabName)
		#app.component.ts
		appComponentTsPath = appPath.join('src').join('app').join('app.component.ts')
		tabNameForPage = tabName[0].upcase + tabName[1..tabName.length - 1]		
		replace(appComponentTsPath, "import { " + tabNameForPage +"Page } from '../pages/" + tabName +"/" + tabName + "';" + "\n" ) { |match| '' }
		replace(appComponentTsPath, /,((?!,)[\S\s])*{ title: '#{originalName}', component: #{tabNameForPage}Page }/) { |match| '' }

		#rootPage
		somePage = get_pages(appPath, appType)[0][0];
		somePage = transform_name(somePage);
		tabNameForSomePage = somePage[0].upcase + somePage[1..somePage.length - 1]		
		replace(appComponentTsPath, "rootPage: any = " + tabNameForPage + "Page;") {|match| "rootPage: any = " + tabNameForSomePage +"Page;"}
		
		#app.module.ts
		moduleTsPath = appPath.join('src').join('app').join('app.module.ts')
		replace(moduleTsPath, "import { " + tabNameForPage +"Page } from '../pages/" + tabName + "/" + tabName + "';" + "\n" ) { |match| '' }
		replace(moduleTsPath, /,((?!,)[\S\s])*#{tabNameForPage}Page/) { |match| '' }

	end

	def self.delete_tab(appPath, originalName, tabName)
		#tabs.html
		tabsPath = appPath.join('src').join('pages').join('tabs').join('tabs.html')
		replace(tabsPath, /<ion-tab \[root\]=\".*\" tabTitle=\"#{originalName}\" tabIcon=\".*\"><\/ion-tab>\n/) { |match| ''}

		#tabs.ts
		tabsTsPath = appPath.join('src').join('pages').join('tabs').join('tabs.ts') 
		tabNameForPage = tabName[0].upcase + tabName[1..tabName.length - 1]
		replace(tabsTsPath, "tab" + tabName + ": any = " + tabNameForPage + "Page;\n") { |match| '' }
		replace(tabsTsPath, "import { " + tabNameForPage +"Page } from '../" + tabName +"/" + tabName + "';" + "\n") { |match|  '' }

		#app.module.ts
		moduleTsPath = appPath.join('src').join('app').join('app.module.ts')
		replace(moduleTsPath, "import { " + tabNameForPage +"Page } from '../pages/" + tabName +"/" + tabName + "';" + "\n" ) { |match| '' }
		replace(moduleTsPath, /,((?!,)[\S\s])*#{tabNameForPage}Page/) { |match| '' }

web-rails/startApp_startup/app/views/mobile_apps/_form.html.erb
<%= form_for @mobile_app, :html => { :class => "form-horizontal mobile_app" } do |f| %>

  <% if @mobile_app.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@mobile_app.errors.count, "error") %> prohibited this mobile_app from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @mobile_app.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "Título", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Descripción", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :apptype, "Tipo de aplicación", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :apptype, ['Tabs','SideMenu'], :selected => @mobile_app.apptype %>
    </div>
    <%=f.error_span(:apptype) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Guardar", :class => 'btn btn-primary', :onclick => 'showLoading()' %>
      <%= link_to t('.cancel', :default => "Cancelar"),
                mobile_apps_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

web-rails/startApp_startup/app/views/mobile_apps/edit.html.erb
<%- model_class = MobileApp -%>
<div class="page-header">
  <h2>Edición de la App</h2>
</div>
<%= render :partial => 'form' %>

web-rails/startApp_startup/app/views/mobile_apps/index.html.erb
<%- model_class = MobileApp -%>
<div class="page-header">
  <h2>Mis Apps</h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= "Título" %></th>
      <th><%= "Descripción" %></th>
      <th><%= "Tipo Aplicación" %></th>
      <th><%= "Fecha de creación" %></th>
      <th><%=t '.actions', :default => "Opciones" %></th>
    </tr>
  </thead>
  <tbody>
    <% @mobile_apps.each do |mobile_app| %>
      <tr>
        <td><%= mobile_app.title %></td>
        <td><%= mobile_app.description %></td>
        <td><%= mobile_app.apptype %></td>
        <td><%= mobile_app.created_at.strftime("%d/%m/%Y") %></td>
        <td>
          <%= link_to t('.screen', :default => "Pantallas"),
                      mobile_apps_menu_path(mobile_app), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.show', :default => "Ver"),
                      mobile_app_path(mobile_app), :class => 'btn btn-default btn-xs', 
                      :onclick => 'showLoading()' %>
          <%= link_to t('.edit', :default => "Editar"),
                      edit_mobile_app_path(mobile_app), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => "Eliminar"),
                      mobile_app_path(mobile_app),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => "Nueva"),
            new_mobile_app_path,
            :class => 'btn btn-primary' %>

web-rails/startApp_startup/app/views/mobile_apps/show.html.erb
<%- model_class = MobileApp -%>

<div class="page-header">
  <div class="right-button">

    <input type="image" src="../assets/settings-icon.png" class="btn btn-default dropdown-toggle" data-toggle="dropdown" width="50px" height="35px" />
    <ul class="dropdown-menu" role="menu">
      <li><%= link_to t('.version', :default => "Versiones anteriores"),versions_index_path(@mobile_app), :target => "_blank" %></li>  
      <li><%= link_to t('.screen', :default => "Pantallas"),mobile_apps_menu_path(@mobile_app), :target => "_blank" %></li>        
      <li><%= link_to t('.notification', :default => "Push notifications"),notifications_index_path(@mobile_app), :target => "_blank" %></li>        
    </ul>
  </div>
  <div >
     <h2><%= @mobile_app.title %></h2>
  </div>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= "Titulo:" %></strong></dt>
  <dd><%= @mobile_app.title %></dd>
  <dt><strong><%= "Descripción:" %></strong></dt>
  <dd><%= @mobile_app.description %></dd>
  <dt><strong><%= "Tipo de aplicación:" %></strong></dt>
  <dd><%= @mobile_app.apptype %></dd>
</dl>

<div class="build-tab-container">

  <center>
  <div class="appPreviewContainer" style="margin-left: 350px;">
    <div class="appPreviewHeadContent"><div><%= Time.zone.now.to_s(:time) %></div></div>
    <iframe id="cellPhoneFrame" src="http://localhost:<%= @mobile_app.port %>" height="500px" width="300px"></iframe>
    
  <div> </center>

<div id="tabPopupApps" style="display: none;">
   
   <div id="contenido">
    
    <div class="modal-header">
        <button id="designPopupCloseButton" type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Agregar tab</h4>
    </div>

    <div id="designPopupErrorMessage" class="alert alert-danger" style="display:none">
      <a href="#" class="close" onclick="hidePopupErrorMessage()">&times;</a>
      <div id="errorMessageDescription"></div>
    </div>

    <div class="form-horizontal">
      <div class="form-group">
        <label class="control-label col-sm-3" for="tab-title">Título:</label>
        <div class="col-sm-9 form-control-div">
          <input id="tab-title" type="text" class="form-control" name="title"> 
        </div>
        </div>
      
      <div class="form-group">
        <label class="control-label col-sm-3" for="tab-type">Tipo:</label>
        <div class="col-sm-9">
          <select id="tab-type" type="text" class="form-control" name="type" onchange="changeFunc();"> 
            <option value="1">Vacía</option>
            <option value="2">Pantalla personalizada</option>
            <option value="3">Facebook</option>
            <option value="4">Instagram</option>
            <option value="5">Twitter</option>
            <option value="6">Youtube</option>
            <option value="7">Foro</option>
            <option value="8">Google maps</option>
            <option value="9">Html de usuario</option>
          </select>
        </div>
      </div>

      <div id="options" class="form-group">
      </div>       

      <div class="form-group"> 
        <div class="col-sm-offset-2 col-sm-10">
          <button id="designPopupSaveButton" class="DesignPopupSaveButton btn btn-default" onclick="saveTab()">Guardar</button>
        </div>
      </div>
    </div>

   </div>
</div>
  <div class="tabs-container">
    <div class="build-tab-section-title">Tabs</div>
      <div class="build-tab-buttons-container" style="overflow-y:auto;"">
      <% get_pages.each do |element| %>
        <div id="div-button" class="build-tab-button-div">
          <span style="margin: auto 1px;line-height:15px;"><%= element[0] %></li> </span>
          <%= link_to t('.tab', :default => "x"),
                  mobile_apps_delete_page_path(:name => element),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => "¿Estas seguro?")) },
                  :class => 'btn btn-tab-danger pull-right' %>
          <!--<%= link_to image_tag("edit-icon.png", :size => "30x20"),  mobile_apps_delete_page_path(:name => element),:class => 'btn btn-tab-edit pull-right' %>-->
        </div>
      <% end %>
      </div>
      <div class = "tab-create-div">
        <button id="showPopupButton" type="button" class="btn btn-default" onclick="showPopup()">Agregar</button>
      </div>
  </div>
</div>
<div class='buttons'>
  <div padding-bottom="30px">
  <%= link_to t('.back', :default => "Volver"),
                mobile_apps_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => "Editar"),
                edit_mobile_app_path(@mobile_app), :class => 'btn btn-default' %>
  <%= link_to t('.build', :default => "Build"), mobile_apps_build_path,
                :class => 'btn btn-build', :method => 'post'%>
  <%= link_to t('.destroy', :default => "Eliminar"),
                mobile_app_path(@mobile_app),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => "¿Estas seguro?")) },
                :class => 'btn btn-danger' %>
  </div>
</div >
<script type="text/javascript">
  $("#designPopupCloseButton").click(function (){
      $("#tabPopupApps").hide();
  })
  function changeFunc(){
    cleanOptions();
    var selectBox = document.getElementById("tab-type");
    var selectedValue = selectBox.options[selectBox.selectedIndex].value;
    if(selectedValue == "2"){
      customScreenClick();
    }
    else if (selectedValue == "3"){
      textInputClick("Página");
    }
    else if (selectedValue == "4"){
      textInputClick("Código de post");
    }
    else if (selectedValue == "5"){
      textInputClick("Url del tweet");
    }
    else if (selectedValue == "6"){
      textInputClick("Canal");
    }
    else if (selectedValue == "8"){
      textInputClick("Map id");
    }
    else if (selectedValue == "9"){
      textInputClick("Html");
    }
  }
  function cleanOptions(){
    var node = document.getElementById('options'); 
    while (node.hasChildNodes()) {
      node.removeChild(node.lastChild);
    }
  }
  function customScreenClick(){
    $("#options").append("<label class=\"control-label col-sm-3\" for=\"custom-screen\">Pantalla:</label><div class=\"col-sm-9\"><select id=\"custom-screen\" type=\"text\" class=\"form-control\"><% @mobile_app.mobile_app_screens.each do |screen| %><option value=<%=screen.id%>><%=screen.name%></option><% end %></select></div><a target=\"_blank\" href=\"/mobile_apps/menu/<%= @mobile_app.id %>\">Ir a ver pantallas</a>");
  }

  function textInputClick(title){
    $("#options").append("<label class=\"control-label col-sm-3\" for=\"custom-screen\">" + title + ":</label><div class=\"col-sm-9\"><input id=\"input-text\" type=\"text\" class=\"form-control\"></input></div>");
  }

  function showPopup(){
    $("#tabPopupApps").show();
  }

  function saveTab(){
    hidePopupErrorMessage();
    //Valido todo
    allFieldsValid = true;
    var title = document.getElementById('tab-title').value; 
    $("#errorMessageDescription").text("");
    if (title == null || title.trim() === ''){
      allFieldsValid = false;
      errorMessage = '<strong>- ';
      errorMessage += "The title should not be empty";
      errorMessage += '</strong>';
      $("#errorMessageDescription").append(errorMessage);
    }
    else{
      var xmlHttp = new XMLHttpRequest();
      xmlHttp.open( "GET", "pages/<%= @mobile_app.id %>/" + title + "/exists", false );
      xmlHttp.send(null);
      var exists = xmlHttp.responseText;
      if(exists === "true"){
        allFieldsValid = false;
        errorMessage = '<strong>- ';
        errorMessage += "Tab " + title + " already exists";
        errorMessage += '</strong>';
        $("#errorMessageDescription").append(errorMessage);
       }

      if (document.getElementById('input-text') && document.getElementById('input-text').value ===''){
        allFieldsValid = false;
        errorMessage = '<strong>- ';
        errorMessage += "Complete all fields";
        errorMessage += '</strong>';
        $("#errorMessageDescription").append(errorMessage);
      }
    }


    if(!allFieldsValid){
      $("#designPopupErrorMessage").show();
      return;
    }
    var tabTypeBox = document.getElementById("tab-type");
    var tabType = tabTypeBox.options[tabTypeBox.selectedIndex].value;
    var freeValue = 1;
    if (document.getElementById('custom-screen')){
      var screenTypeBox = document.getElementById("custom-screen");
      freeValue = screenTypeBox.options[screenTypeBox.selectedIndex].value;
    } else if (document.getElementById('input-text')){
      var inputText = document.getElementById("input-text");
      freeValue = inputText.value;
    }
    
    $.ajax({
      type: "POST",
      url: "/mobile_apps/pages/<%= @mobile_app.id %>/" + title,
      data: { type: tabType, value : freeValue} 
    });
    if (window.location.href.indexOf("?s=f") == -1){
      window.location.href = window.location.href + "?s=f";
      window.location.load();
    }
    else{
      location.reload();   
    }
  }

  function hidePopupErrorMessage(){   
    $("#designPopupErrorMessage strong").each(function(){
      $(this).remove();
    });
    $("#designPopupErrorMessage").hide();
  }

  // window.onload = function() {
  //   if(window.location.href.indexOf("s=f") > -1) {
  //     var iframe = document.getElementById('cellPhoneFrame');
  //     iframe.src = iframe.src;
  //   }
  // };  

</script>