web-rails/startApp_startup/config/routes.rb
Rails.application.routes.draw do
  
  resources :mobile_app_screens
  resources :mobile_apps
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', 
                                    passwords: 'users/passwords',
                                    :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'welcome/index'
  match '/mobile_apps/build/:id', to: 'mobile_apps#build', as: 'build', :via => [:get,:post], :as => :mobile_apps_build
  match '/mobile_apps/:id', to: 'mobile_apps#show', as: 'show', :via => [:get ], :as => :mobile_apps_show
  match '/mobile_apps/pages/:id/:name', to: 'mobile_apps#new_page', as: 'new_tab', :via => [:get,:post], :as => :mobile_apps_new_page
  match '/mobile_apps/pages/:id/:name', to: 'mobile_apps#delete_page', as: 'delete_page', :via => [:delete], :as => :mobile_apps_delete_page
  match '/mobile_apps/content/:id/:name', to: 'mobile_apps#set_content', as: 'set_content', :via => [:get,:post], :as => :mobile_apps_set_content
  match '/mobile_apps/pages/:id/:name/exists', to: 'mobile_apps#page_exists', as: 'page_exists', :via => [:get], :as => :mobile_apps_page_exists
  match '/versions/:id', to: 'versions#update', as: 'version_update', :via => [:post], :as => :versions_update
  match '/versions/restore/:id', to: 'versions#restore', as: 'version_restore', :via => [:post], :as => :versions_restore
  match '/versions/:id', to: 'versions#index', as: 'versions_index', :via => [:get], :as => :versions_index
  match '/versions/new/:id', to: 'versions#new', as: 'versions_new', :via => [:get, :post], :as => :versions_new

  match '/notifications/:id', to: 'notifications#update', as: 'notification_update', :via => [:post], :as => :notifications_update
  match '/notifications/:id', to: 'notifications#index', as: 'notification_index', :via => [:get], :as => :notifications_index
  match '/notifications/new/:id', to: 'notifications#new', as: 'notification_new', :via => [:get, :post], :as => :notifications_new

  
  match '/mobile_apps/menu/:id', to: 'mobile_apps#menu', as: 'menu', :via => [:get,:post], :as => :mobile_apps_menu

  resources :versions
  resources :notifications

  root 'welcome#index'

end

web-rails/startApp_startup/app/models/version.rb
class Version < ActiveRecord::Base
	belongs_to :mobile_app

	validates :description, presence: { message: " is required" }
end

web-rails/startApp_startup/app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :set_version, only: [:show, :edit, :update, :destroy, :restore]
  before_action :set_mobile_app, only: [:index, :new]

  layout "application_internal_styled"

  # GET /versions
  # GET /versions.json
  def index
    if(@mobile_app.user_id.equal? current_user.id)
      @versions = Version.all.where(mobile_app: @mobile_app)
    end
  end

  # GET /versions/1
  # GET /versions/1.json
  def show
  end

  # GET /versions/new
  def new
    @version = Version.new
  end

  # GET /versions/1/edit
  def edit
    @mobile_app = MobileApp.find(@version.mobile_app_id)
  end

  # POST /versions
  # POST /versions.json
  def create
    @version = Version.new(version_params)
    @mobile_app = MobileApp.find(@version.mobile_app_id)
    if(@mobile_app.user_id.equal? current_user.id)
      respond_to do |format|
        if @version.save
          backupPath = Rails.root.join('versions').join(current_user.id.to_s).join(@version.mobile_app.title).join(@version.description) 
          FileUtils.mkdir_p(backupPath) unless File.directory?(backupPath)
          appPath = Rails.root.join('mobileApps').join(current_user.id.to_s).join(@version.mobile_app.title).join('*')
          FileUtils.cp_r Dir[appPath] , backupPath

          format.html { redirect_to versions_url + "/" + @version.mobile_app_id.to_s, notice: 'Version creada exitosamente.' }
          format.json { render :show, status: :created, location: @version }
        else
          format.html { render :new }
          format.json { render json: @version.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /versions/1
  # PATCH/PUT /versions/1.json
  def update
    @mobile_app = MobileApp.find(@version.mobile_app_id)
    if(@mobile_app.user_id.equal? current_user.id)
      @oldVersion = Version.find(@version.id)
      oldDescription = @oldVersion.description
      respond_to do |format|
        if @version.update(version_params)
          oldBackupPath = Rails.root.join('versions').join(current_user.id.to_s).join(@version.mobile_app.title).join(oldDescription)
          newBackupPath = Rails.root.join('versions').join(current_user.id.to_s).join(@version.mobile_app.title).join(@version.description) 
          File.rename oldBackupPath, newBackupPath
          format.html { redirect_to versions_url + "/" + @version.mobile_app_id.to_s, notice: 'Version actualizada exitosamente.' }
          format.json { render :show, status: :ok, location: @version }
        else
          format.html { render :edit }
          format.json { render json: @version.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /versions/1
  # DELETE /versions/1.json
  def destroy
    @mobile_app = MobileApp.find(@version.mobile_app_id)
    if(@mobile_app.user_id.equal? current_user.id)
      mobile_app_id = @version.mobile_app_id.to_s
      versionPath = Rails.root.join('versions').join(current_user.id.to_s).join(@version.mobile_app.title).join(@version.description) 
      FileUtils.rm_rf(versionPath)
      @version.destroy
      respond_to do |format|
        format.html { redirect_to versions_url + "/" + @version.mobile_app_id.to_s, notice: 'Version eliminada exitosamente.' }
        format.json { head :no_content }
      end
    end
  end

  def restore
    if(@version.mobile_app.user_id.equal? current_user.id)
      appPath = Rails.root.join('mobileApps').join(current_user.id.to_s).join(@version.mobile_app.title)
      versionPath = Rails.root.join('versions').join(current_user.id.to_s).join(@version.mobile_app.title).join(@version.description)
      if(File.directory?(versionPath))
        FileUtils.rm_rf(appPath)
        FileUtils.copy_entry versionPath, appPath
        respond_to do |format|
          format.html { redirect_to @version.mobile_app, notice: 'Version ' + @version.description + ' restaurada exitosamente.' }
          format.json { render :show, status: :created, location: @version.mobile_app }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_version
      @version = Version.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def version_params
      params.require(:version).permit(:description, :mobile_app_id)
    end

    def set_mobile_app
      if (params[:id])
        @mobile_app = MobileApp.find(params[:id])
        if(!@mobile_app.user_id.equal? current_user.id)
          raise "error"
        end
      end
    end
end

web-rails/startApp_startup/app/helpers/versions_helper.rb
module VersionsHelper
end

web-rails/startApp_startup/app/views/versions/_form.html.erb
<%= form_for @version, :html => { :class => "form-horizontal notification" } do |f| %>
  <% if @version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@version.errors.count, "error") %> prohibited this version from being saved:</h2>

      <ul>
      <% @version.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description, "Descripción", :class => 'control-label col-lg-2'  %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control'   %>
    </div>
  </div>
  <div class="field">
    <%= f.hidden_field :mobile_app_id, :value => @mobile_app.id%>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit %>
    </div>
  </div>
<% end %>

web-rails/startApp_startup/app/views/versions/edit.html.erb
<%- model_class = Version -%>
<div class="row internalRow">
	<%= bootstrap_flash %>
	<div class="col-lg-12 internalContent">
		<div class="page-header">
		  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Versión'], :model => model_class.model_name.human.titleize %></h1>
		</div>

		<%= render 'form' %>
	</div>
</div>

web-rails/startApp_startup/app/views/versions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Versiones anteriores de <%= @mobile_app.title %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Descripción</th>
      <th>Fecha de creación</th>
      <th><%=t '.actions', :default => "Opciones" %></th>
    </tr>
  </thead>

  <tbody>
    <% @versions.each do |version| %>
      <tr>
        <td><%= version.description %></td>
        <td><%= version.created_at.strftime("%d/%m/%Y") %></td>
        <td>
        <%= link_to t('.restore', :default => "Restaurar"),
                      versions_restore_path(version.id), 
                      :method => :post,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-default btn-xs', :onclick => 'showLoading()'   %>
        <%= link_to t('.edit', :default => "Editar"),
                      edit_version_path(version), :class => 'btn btn-default btn-xs' %>
        <%= link_to t('.destroy', :default => "Eliminar"),
                      version_path(version),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to t('.new', :default => "Nueva"),
            new_version_path + "/" + @mobile_app.id.to_s,
            :class => 'btn btn-primary' %>

web-rails/startApp_startup/app/views/versions/new.html.erb
<%- model_class = Version -%>
<div class="row internalRow">
	<%= bootstrap_flash %>
	<div class="col-lg-12 internalContent">
		<div class="page-header">
		  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Nueva versión'], :model => model_class.model_name.human.titleize %></h1>
		</div>

		<%= render 'form' %>
	</div>
</div>

web-rails/startApp_startup/app/views/versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @version.description %>
</p>

<p>
  <strong>Mobile app:</strong>
  <%= @version.mobile_app_id %>
</p>

<%= link_to 'Edit', edit_version_path(@version) %> |
<%= link_to 'Back', versions_path %>