web-rails/startApp_startup/config/routes.rb
Rails.application.routes.draw do
  
  resources :mobile_app_screens
  resources :mobile_apps
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', 
                                    passwords: 'users/passwords',
                                    :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'welcome/index'
  match '/mobile_apps/build/:id', to: 'mobile_apps#build', as: 'build', :via => [:get,:post], :as => :mobile_apps_build
  match '/mobile_apps/:id', to: 'mobile_apps#show', as: 'show', :via => [:get ], :as => :mobile_apps_show
  match '/mobile_apps/pages/:id/:name', to: 'mobile_apps#new_page', as: 'new_tab', :via => [:get,:post], :as => :mobile_apps_new_page
  match '/mobile_apps/pages/:id/:name', to: 'mobile_apps#delete_page', as: 'delete_page', :via => [:delete], :as => :mobile_apps_delete_page
  match '/mobile_apps/content/:id/:name', to: 'mobile_apps#set_content', as: 'set_content', :via => [:get,:post], :as => :mobile_apps_set_content
  match '/mobile_apps/pages/:id/:name/exists', to: 'mobile_apps#page_exists', as: 'page_exists', :via => [:get], :as => :mobile_apps_page_exists
  match '/versions/:id', to: 'versions#update', as: 'version_update', :via => [:post], :as => :versions_update
  match '/versions/restore/:id', to: 'versions#restore', as: 'version_restore', :via => [:post], :as => :versions_restore
  match '/versions/:id', to: 'versions#index', as: 'versions_index', :via => [:get], :as => :versions_index
  match '/versions/new/:id', to: 'versions#new', as: 'versions_new', :via => [:get, :post], :as => :versions_new

  match '/notifications/:id', to: 'notifications#update', as: 'notification_update', :via => [:post], :as => :notifications_update
  match '/notifications/:id', to: 'notifications#index', as: 'notification_index', :via => [:get], :as => :notifications_index
  match '/notifications/new/:id', to: 'notifications#new', as: 'notification_new', :via => [:get, :post], :as => :notifications_new

  
  match '/mobile_apps/menu/:id', to: 'mobile_apps#menu', as: 'menu', :via => [:get,:post], :as => :mobile_apps_menu

  resources :versions
  resources :notifications

  root 'welcome#index'

end

web-rails/startApp_startup/app/models/notification.rb
class Notification < ActiveRecord::Base
	belongs_to :mobile_app

	validates :message, presence: { message: " is required" }
	validates :action_date, presence: { message: " is required" }
end

web-rails/startApp_startup/app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]
  before_action :set_mobile_app, only: [:index, :new]

  layout "application_internal_styled"

  # GET /notifications
  # GET /notifications.json
  def index
    if(@mobile_app.user_id.equal? current_user.id)
      @notifications = Notification.all.where(mobile_app: @mobile_app)
    end
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
    @mobile_app = MobileApp.find(@notification.mobile_app_id)
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)
    @notification.sent = false;
    @mobile_app = MobileApp.find(@notification.mobile_app_id)
    if(@mobile_app.user_id.equal? current_user.id)  
      respond_to do |format|
        if @notification.save
          format.html { redirect_to notifications_url + "/" + @notification.mobile_app_id.to_s, notice: 'Notificacion creada exitosamente.' }
          format.json { render :show, status: :created, location: @notification }
        else
          format.html { render :new }
          format.json { render json: @notification.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    @mobile_app = MobileApp.find(@notification.mobile_app_id)
    if(@mobile_app.user_id.equal? current_user.id)
      respond_to do |format|
        if @notification.update(notification_params)
          format.html { redirect_to notifications_url + "/" + @notification.mobile_app_id.to_s, notice: 'Notificacion actualizada exitosamente.' }
          format.json { render :show, status: :ok, location: @notification }
        else
          format.html { render :edit }
          format.json { render json: @notification.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @mobile_app = MobileApp.find(@notification.mobile_app_id)
    if(@mobile_app.user_id.equal? current_user.id)
      @notification.destroy
      respond_to do |format|
        format.html { redirect_to notifications_url + "/" + @notification.mobile_app_id.to_s, notice: 'Notificacion destruida exitosamente.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:message, :title, :mobile_app_id, :action_date)
    end

    def set_mobile_app
      if (params[:id])
        @mobile_app = MobileApp.find(params[:id])
        if(!@mobile_app.user_id.equal? current_user.id)
          raise "error"
        end
      end
    end
end

web-rails/startApp_startup/app/helpers/notifications_helper.rb
module NotificationsHelper
end

web-rails/startApp_startup/app/views/notifications/_form.html.erb
<%= form_for @notification, :html => { :class => "form-horizontal notification" } do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "Title" , :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control'  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :message, "Mensaje" , :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :message, :class => 'form-control'  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :action_date, "Fecha de envío" , :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :action_date %>
    </div>
  </div>
  <div class="field">
    <%= f.hidden_field :mobile_app_id, :value => @mobile_app.id%>
  </div>
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Guardar push notification" %>
    </div>
  </div>
<% end %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>                       
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />



<script type="text/javascript">

var ready = function() {
    $('#notification_action_date').datetimepicker({ format:'DD/MM/YYYY HH:mm A' });
    
      $('#notification_action_date').val("<%= if(@notification.action_date)
           @notification.action_date.strftime("%d/%m/%Y %H:%M %p");
        end %>");
    
};

$(document).ready(ready);
$(document).on('page:change', ready);


</script>

web-rails/startApp_startup/app/views/notifications/edit.html.erb
<%- model_class = Notification -%>
<div class="row internalRow">
	<%= bootstrap_flash %>
	<div class="col-lg-12 internalContent">
		<div class="page-header">
		  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Push notification'], :model => model_class.model_name.human.titleize %></h1>
		</div>
		<%= render :partial => 'form' %>

	</div>
</div>

web-rails/startApp_startup/app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Push Notifications de <%= @mobile_app.title %> </h1> 

<table class="table table-striped">
  <thead>
    <tr>
      <th>Título</th>
      <th>Mensaje</th>
      <th>Fecha de envío</th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.title %></td>
        <td><%= notification.message %></td>
        <td><%= notification.action_date.strftime("%d/%m/%Y %H:%M %p") %></td>
        <td><%= notification.sent %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new', :default => "Nueva push notification"),
            new_notification_path + "/" + @mobile_app.id.to_s,
            :class => 'btn btn-primary', method: :get %>

web-rails/startApp_startup/app/views/notifications/new.html.erb
<%- model_class = Notification -%>
<div class="row internalRow">
	<%= bootstrap_flash %>
	<div class="col-lg-12 internalContent">
		<div class="page-header">
		  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Nueva push notification'], :model => model_class.model_name.human.titleize %></h1>
		</div>
		<%= render :partial => 'form' %>

	</div>
</div>

web-rails/startApp_startup/app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @notification.message %>
</p>

<p>
  <strong>Mobile app:</strong>
  <%= @notification.mobile_app_id %>
</p>

<p>
  <strong>Action date:</strong>
  <%= @notification.action_date %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>