web-rails/startApp_startup/config/routes.rb
Rails.application.routes.draw do
  
  resources :mobile_app_screens
  resources :mobile_apps
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', 
                                    passwords: 'users/passwords',
                                    :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'welcome/index'
  match '/mobile_apps/build/:id', to: 'mobile_apps#build', as: 'build', :via => [:get,:post], :as => :mobile_apps_build
  match '/mobile_apps/:id', to: 'mobile_apps#show', as: 'show', :via => [:get ], :as => :mobile_apps_show
  match '/mobile_apps/pages/:id/:name', to: 'mobile_apps#new_page', as: 'new_tab', :via => [:get,:post], :as => :mobile_apps_new_page
  match '/mobile_apps/pages/:id/:name', to: 'mobile_apps#delete_page', as: 'delete_page', :via => [:delete], :as => :mobile_apps_delete_page
  match '/mobile_apps/content/:id/:name', to: 'mobile_apps#set_content', as: 'set_content', :via => [:get,:post], :as => :mobile_apps_set_content
  match '/mobile_apps/pages/:id/:name/exists', to: 'mobile_apps#page_exists', as: 'page_exists', :via => [:get], :as => :mobile_apps_page_exists
  match '/versions/:id', to: 'versions#update', as: 'version_update', :via => [:post], :as => :versions_update
  match '/versions/restore/:id', to: 'versions#restore', as: 'version_restore', :via => [:post], :as => :versions_restore
  match '/versions/:id', to: 'versions#index', as: 'versions_index', :via => [:get], :as => :versions_index
  match '/versions/new/:id', to: 'versions#new', as: 'versions_new', :via => [:get, :post], :as => :versions_new

  match '/notifications/:id', to: 'notifications#update', as: 'notification_update', :via => [:post], :as => :notifications_update
  match '/notifications/:id', to: 'notifications#index', as: 'notification_index', :via => [:get], :as => :notifications_index
  match '/notifications/new/:id', to: 'notifications#new', as: 'notification_new', :via => [:get, :post], :as => :notifications_new

  
  match '/mobile_apps/menu/:id', to: 'mobile_apps#menu', as: 'menu', :via => [:get,:post], :as => :mobile_apps_menu

  resources :versions
  resources :notifications

  root 'welcome#index'

end

web-rails/startApp_startup/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


  <title>StartAppStartup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

web-rails/startApp_startup/app/views/layouts/application_internal_styled.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "App & Ready" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>


    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbarCustom navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">App & Ready</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to "Mis apps", mobile_apps_path %><li>
              <li class="divider"></li>
              <li class="dropdown userMenu">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.email %>
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Cambiar contraseña", edit_user_registration_path %></li>
                  <li><%= link_to "Salir", destroy_user_session_path, :method => :delete  %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Ingresar", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="mainContainerCustom container">
      <div class="row internalRow">
        <%= bootstrap_flash %>
        <div class="col-lg-12 internalContent">
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->
  </body>
  <div id="loading" style="display:none;">
    <img id="loading-image" src="../assets/loading_icon.gif" alt="Loading..." />
  </div>
</html>

web-rails/startApp_startup/app/views/layouts/application_styled.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "App & Ready" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbarCustom navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">App & Ready</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to "Mis apps", mobile_apps_path %><li>
              <li class="divider"></li>
              <li class="dropdown userMenu">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.email %>
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Cambiar contraseña", edit_user_registration_path %></li>
                  <li><%= link_to "Salir", destroy_user_session_path, :method => :delete  %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Ingresar", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="mainContainerCustom container">
      <div class="row">
        <%= bootstrap_flash %>
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->
  </body>
</html>